### ISSUE TITLE
What happens after the 3 month beta pricing?

### ISSUE THREAD

**Issue by thinkh** [fossapps/pr_label_enforcer#20]
The [GitHub Marketplace page](https://github.com/marketplace/pr-label-enforcer) states that you can test the beta version for free for 3 month and "after beta pricing is done, simply upgrade to premium or free". 

![grafik](https://user-images.githubusercontent.com/5851088/73369981-cb8fce80-42b3-11ea-83c2-77d3f562dfec.png)

What will happen after these 3 month? How much will it cost afterwards (for closed source repositories)?

**Comment by cyberhck** [comment]
well, I haven't implemented that part, but I'm planning to do so soon, meanwhile feel free to use it, after which I think I'll do somewhere like $2/month for closed repositories, I haven't decided that either.

**Comment by thinkh** [comment]
Thanks for your answer and the pointer to the Docker container. :)
